### ISSUE TITLE
Eigen.h file is missing

### ISSUE THREAD

**Issue by frozenmafia** [bolderflight/invensense-imu#100]
I am trying to use this library with esp32 but compiler shows eigen.h is missing.

**Comment by flybrianfly** [comment]
Can you post the full outputs from Arduino? I don't have an ESP32 to test against.

**Comment by frozenmafia** [comment]
![Screenshot 2022-02-26 094659](https://user-images.githubusercontent.com/63967971/155828565-adf12077-d704-4693-8ce0-da917d150447.png)
This is not compiling. Problem is that Eigen.h is missing.
[Here in mpu9250.h eigen.h is included](https://github.com/bolderflight/mpu9250/blob/01d19b8c086243170125a2d2dfb437353d30bd28/src/mpu9250.h#L38)

But there is [no file in named eigen.h ](https://github.com/bolderflight/mpu9250/tree/main/src).
I have just switched from atmega328p to esp32 and this library is my last hope 
Thanks for replying

**Comment by frozenmafia** [comment]
![Screenshot 2022-02-26 094659](https://user-images.githubusercontent.com/63967971/155828565-adf12077-d704-4693-8ce0-da917d150447.png)
This is not compiling. Problem is that Eigen.h is missing.
[Here in mpu9250.h eigen.h is included](https://github.com/bolderflight/mpu9250/blob/01d19b8c086243170125a2d2dfb437353d30bd28/src/mpu9250.h#L38)

But there is [no file in named eigen.h ](https://github.com/bolderflight/mpu9250/tree/main/src).
I have just switched from atmega328p to esp32 and this library is my last hope 
Thanks for replying

**Comment by flybrianfly** [comment]
Please check the [Installation instructions](https://github.com/bolderflight/mpu9250#arduino), you need to install the the [Bolder Flight Systems Units library](https://github.com/bolderflight/units) and the [Bolder Flight Systems Eigen library](https://github.com/bolderflight/eigen) for this library to compile.

**Comment by frozenmafia** [comment]
Thanks it worked! Next time I will read instructions more carefully.
