### ISSUE TITLE
 No such file or directory  #include <cstddef> + a few more imports

### ISSUE THREAD

**Issue by 19valentin99** [bolderflight/invensense-imu#103]
![image](https://user-images.githubusercontent.com/27396461/158307315-92abd114-e01b-46e9-9f35-ea8f06449906.png)

Hello, I am trying to import the library but I find that I get an error and I am not sure why. 
I tried to have a look into it but I didn't get any useful results.
Furthermore I had a look into the source code and I found a few more imports that I am missing and I couldn't find them in the Arduino Manage Librarie, such as
- #include \<cmath>
- #include \<cstddef>
- #include \<cstdint>
- #include \<algorithm>

Furthermore, the board that I am using is Arduino Mega 2560.
I would be grateful if you could help me to solve this problem.

Thank you very much.

**Comment by flybrianfly** [comment]
Hi, if you look at the [installation instructions](https://github.com/bolderflight/mpu9250/#arduino), you'll notice that the library is no longer compatible with AVR microprocessors, which is what the Arduino Mega is. You may want to try an older version of the library or a different library.
