### ISSUE TITLE
Latest version of the library is not available in PlatformIO library registry.

### ISSUE THREAD

**Issue by ErfanMoosaviMonazzah** [bolderflight/invensense-imu#104]
Hi, Is there any plan to update the library on PIO library registry? [Current last version is 1.0.2 at here](https://registry.platformio.org/libraries/bolderflight/Bolder%20Flight%20Systems%20MPU9250/versions).

**Comment by flybrianfly** [comment]
I've never used Platform IO and don't know the process for updating the PIO library registry. I'd be open to supporting someone to update my libraries on there, but I don't have the bandwidth to learn another system if I'm not regularly using it.
