### ISSUE TITLE
cstddef: No such file or directory

### ISSUE THREAD

**Issue by NipunDewthilina** [bolderflight/invensense-imu#108]
When I run the I2C program, it gives this error

fatal error: cstddef: No such file or directory
 #include <cstddef>
          ^~~~~~~~~
How do I solve this? Please help

**Comment by flybrianfly** [comment]
I suspect that you're trying to use this library on an AVR microcontroller, which is not supported by the current version of this library. You can try using some older versions, which do support AVR.
