### ISSUE TITLE
cstddef & cstdint?

### ISSUE THREAD

**Issue by Vallejoooooooo** [bolderflight/invensense-imu#109]
When I try to compile it gives me the following error:

In file included from C:\Users\34683\OneDrive\Documentos\Cansat\CANSAT-PFe\CodigoArduino\CodigoArduino.ino:1:0:
C:\Users\34683\OneDrive\Documentos\Arduino\libraries\Bolder_Flight_Systems_MPU9250\src/mpu9250.h:36:10: fatal error: cstdint: No such file or directory
 #include <cstdint>
          ^~~~~~~~~
compilation terminated.
exit status 1
Error compilando para la tarjeta Arduino Uno.

**Comment by flybrianfly** [comment]
Please see the [installation instructions](https://github.com/bolderflight/mpu9250#arduino), AVR microcontrollers such as Arduino Uno are not supported with the newest release of the library, you might try some older releases to see if they'll work for you.
