### ISSUE TITLE
Set SPI clock speed

### ISSUE THREAD

**Issue by tcerqueira** [bolderflight/invensense-imu#110]
I'm using an array of mpu9250 and a teensy4.0 and the default speed was inconsistent. Probably the longer wires, multiple sensors on the bus and maybe the teensy SPI known problems limits the max operating speed and lowering it seemed to do the trick.
However it is hardcoded and I would consider some way to set the speed. Not a big deal tho.
Thanks for this lib!

**Comment by flybrianfly** [comment]
Thanks for the suggestion!
