### ISSUE TITLE
how can i get the cstddef

### ISSUE THREAD

**Issue by alexspace360** [bolderflight/invensense-imu#117]
In file included from C:\Users\dream\AppData\Local\Temp\.arduinoIDE-unsaved2023217-8988-1vhfcel.y73jj\i2c\i2c.ino:26:0:
C:\Users\dream\Documents\Arduino\libraries\Bolder_Flight_Systems_MPU9250\src/mpu9250.h:36:10: fatal error: cstddef: No such file or directory
 #include <cstddef>
          ^~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by flybrianfly** [comment]
Please try downloading and using the latest version from GitHub.

**Comment by alexspace360** [comment]
may you tell me how to install it from github  ?  i downloaded the files 

> Please try downloading and using the latest version from GitHub.

**Comment by alexspace360** [comment]
thanks
