### ISSUE TITLE
 status -5

### ISSUE THREAD

**Issue by Narek-939** [bolderflight/invensense-imu#119]
Hi, please help me, I get the error with status -5, and if my IMU is not MPU9250, how I can resolve this issue

**Comment by flybrianfly** [comment]
1. You're using a really old version of the library, please download the latest directly from GitHub.
2. Only the MPU-9250, MPU-92500, and MPU-6500 are currently supported.

**Comment by Narek-939** [comment]
Thank you) I changed my lib version, but I encountered the other Error initializing communication with IMU,
is it connected with my IMU or Arduino nano V3.0???

**Comment by flybrianfly** [comment]
Which InvenSense IMU are you using? This library only works with the MPU-9250, MPU-9255, and MPU-6500.

**Comment by Narek-939** [comment]
I am using the MPU9250
