### ISSUE TITLE
Motion Apps

### ISSUE THREAD

**Issue by flybrianfly** [bolderflight/invensense-imu#17]
Add AHRS and / or DMP.

**Comment by bingcheng1998** [comment]
Hey! 
Thanks for your fantastic work! It helps me a lot.
I tried to add DMP to the library myself, but I failed.
Your code works well!

**Comment by bingcheng1998** [comment]
[BUG] e... It looks that something went wrong...
```c++
  Serial.print(hx,6);
  Serial.print("\t");
  Serial.print(hy,6);
  Serial.print("\t");
  Serial.print(hz,6);
  Serial.print("\t");
```
h output doesn't change at all.
![](http://ww1.sinaimg.cn/large/006tNc79ly1g36g4kz8tfj31xu0q2thz.jpg)

**Comment by jedjoud10** [comment]
Would it even be possible to add DMP support? I'm not even sure that the MPU 9050 has a DMP because I see no documentation about it online at all

**Comment by draeron** [comment]
not sure about the MPU9050 but the MPU9150 does, there ain't much documentation on it though.

https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU9150

**Comment by flybrianfly** [comment]
The MPU-9250 does have DMP, but we're not planning to add it at this time.
