### ISSUE TITLE
How to wire MPU9250 breakout board to arduino in SPI Mode

### ISSUE THREAD

**Issue by maweUkuta** [bolderflight/invensense-imu#22]
I am wondering how to wire the MPU9250 breakout board to Arduino in SPI Mode. Right now I have
Vcc - 3.3v
Gnd - Gnd
SCL - 13
SDA - 11
ADO - 12
NCS - 10

**Comment by flybrianfly** [comment]
Which breakout board and which arduino? This is generic information on how to wire for SPI:
https://github.com/bolderflight/MPU9250#spi
