### ISSUE TITLE
Right order of axis for AHRS

### ISSUE THREAD

**Issue by CoWayger** [bolderflight/invensense-imu#24]
Hello, anyone here tried to use this library coordinate system to get working quaternion with madwick? I have seen [this](https://raw.githubusercontent.com/kriswiner/LSM9DS0/master/Teensy3.1/LSM9DS0-MS5637/quaternionFilters.ino) implementation, but it seems that it uses NED reference frame. How can i convert your reference system to NED? 

`mFilterMadwick.update( elapsed,
					acceleration.x, acceleration.y, acceleration.z,
					gyroCalibrated.x, gyroCalibrated.y, gyroCalibrated.z,
					mCompassCalibrated.x, mCompassCalibrated.y, mCompassCalibrated.z
				);`

**Comment by flybrianfly** [comment]
The MPU-9250 reference frame is a standard body fixed frame. In fact, you can't directly transform to an inertial frame, like NED, without some kind of estimation technique, which is what Madgwick, Mahony, and Kalman filtering is used for. Unfortunately, the script you're pointing to is using the raw MPU-9250 output and keeping the misalignment between the IMU and magnetometer. There's a good discussion here about reference frames and getting Madgwick to work with a standard body fixed frame:
https://forum.pjrc.com/threads/48450-uNav-AHRS?p=167092&viewfull=1#post167092
