### ISSUE TITLE
Does this library utilize Kalman filter or similar algorithm?

### ISSUE THREAD

**Issue by Patrickyp** [bolderflight/invensense-imu#28]
Does this library use Kalman filter or any other similar algorithms to get more accurate results from the mpu?

**Comment by flybrianfly** [comment]
Not currently. However, gyro biases are estimated on startup and methods are provide to estimate accelerometer and magnetometer bias and scale factor terms. There are also INS (https://github.com/bolderflight/uNavINS) and AHRS (https://github.com/bolderflight/uNavAHRS) filters available which estimate IMU biases over time; although, these filters are still a work in progress. Finally, a lot of discussion is on the PJRC forum regarding INS and AHRS filtering as well as updating bias estimates in real time:
https://forum.pjrc.com/threads/37891-MPU-9250-Teensy-Library?highlight=mpu9250
https://forum.pjrc.com/threads/48856-uNav-INS?highlight=mpu9250
https://forum.pjrc.com/threads/48450-uNav-AHRS?highlight=mpu9250

Long term, I'd like to add an AHRS to this library...
