### ISSUE TITLE
adding new generation filters

### ISSUE THREAD

**Issue by aster94** [bolderflight/invensense-imu#3]
hello
did you thought to add a filtering?
examples:
https://github.com/kriswiner/MPU9250/blob/master/quaternionFilters.ino
or the improved sparkfun version:
https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library

i tried myself but i wasn't able to do it

**Comment by balzss** [comment]
I don't know if you still has the issue but try adding a "timer" to your code that keeps track of the sample frequency because the madgwick algorithm requires a delta_t parameter. Otherwise it should work without any problem.

**Comment by aster94** [comment]
hello, i solved it. thank you anyway for the message :)
