### ISSUE TITLE
Problems working with madgwick quaternion filter

### ISSUE THREAD

**Issue by hcklawrence** [bolderflight/invensense-imu#30]
Hi,
I am working on a small project using MPU9250 to get rotational data of the joint. As I utilizting this library with Madgwick quaternion filter, I got a very strange result, which not only drift when stationary, but also when I'm moving the sensor. (a short video showing the result: https://youtu.be/sDa7cdnEAwQ) 

I guess the code for the filter is correct since it is open source and online everywhere. (In my working repo lib: https://github.com/larryyyyy/MPU9250) I was stucking in this stage to get a good quaternion for so long like several weeks... hope to get some hins here. Thank you so much!

**Comment by Lynxu** [comment]
I'm having the same problem did you find any fixes for this?
