### ISSUE TITLE
No matching function call to MPU9250  :: Solved

### ISSUE THREAD

**Issue by ZeroRadius** [bolderflight/invensense-imu#40]
I am trying to compile Basic_I2C and am receiving the following  error 

> No Matching function for call to 'MPU9250_<TwoWire>::MPU9250_(TwoWire&, int)'

I am using Arduino uno, Arduino IDE 1.8.7 , I installed via the library manager and the IDE installed it for me.  I opened the sketch via the examples menu

**Comment by ZeroRadius** [comment]
The problem was i had another library with a MPU9250.h file and it was reading that file. Still won't compile for my uno but it did get past this issue

**Comment by flybrianfly** [comment]
I just tried compiling this library for Uno and it should work.
