### ISSUE TITLE
ACCEL_RANGE is ignored

### ISSUE THREAD

**Issue by maikischa** [bolderflight/invensense-imu#42]
When I set the Accel Range with `IMU.setAccelRange(MPU9250::ACCEL_RANGE_4G);` the statement is ignored and all readings I get are limited to 20 m/s/s (2G).
I have tried different ranges but always get only maximum 2G readings.

**Comment by maikischa** [comment]
In addition I found out that the ACCEL_RANGE is only rested to 2G if I run `IMU.calibrateAccel()`.

It seems that `IMU.calibrateAccel()` resets the ACCEL_RANGE to 2G

**Comment by Reobos** [comment]
I noticed in the code the calibrate functions do not properly restore settings after changing them for the calibration. I made a fix in pull request #76 which should actually restore settings.

**Comment by flybrianfly** [comment]
Removed calibration from the library, the accel range should be set correctly now.
