### ISSUE TITLE
Calibration of the magnetometer does not work

### ISSUE THREAD

**Issue by alexmekh** [bolderflight/invensense-imu#43]
In a magnetometer calibration, the _hxfilt, _hyfilt, _hzfilt value is always 0.0. Since they are initialized by 0.0 and multiplied by them.

**Comment by flybrianfly** [comment]
If you look at the relevant equation: 
`_hxfilt = (_hxfilt*((float)_coeff-1)+(getMagX_uT()/_hxs+_hxb))/((float)_coeff);`

You'll see that _hxfilt is only multiplied by the first term - this is the equation of a first order IIR filter. So, as long as readSensor() is correctly reading the MPU-9250, getMagX_uT() will return the measured x axis magnetic field strength and the filter will be updated.

If you simply begin communications with the sensor and call readSensor, are you getting good magnetic values? Are begin and readSensor returning positive values, indicating successful initialization and reading?

**Comment by alexmekh** [comment]
I used FIFO reading to increase speed (processor weak at89c51ed2). I had a mistake. Thank.
