### ISSUE TITLE
ESP32 and SPI connection: corrupt accelerometer and magnetometer values 

### ISSUE THREAD

**Issue by jtec** [bolderflight/invensense-imu#46]
Hi, 

Issue:
when using the library with an ESP32 connected via SPI, accelerometer and magnetometer values are corrupt. Example: Serial.print(IMU->getAccelX_mss(),6) prints "ovf".

Reason: 
When not performing a calibration, numerous values for accelerometer biases such as "_axb" etc. defined in  MPU9250.h are not initialized.

**Comment by flybrianfly** [comment]
Please post the code that you are running and getting ovf.

**Comment by jtec** [comment]
Hi, 

the following Arduino code

```c
#include "MPU9250.h"
MPU9250* IMU = NULL;
SPIClass * vspi = NULL;

void setup(void) {
  Serial.begin(115200);
  vspi = new SPIClass(VSPI);
  // SCLK = 18, MISO = 19, MOSI = 23, SS = 5
  vspi->begin();
  IMU = new MPU9250(*vspi, 33);
}

void loop(void) {
  delay(1000);
  IMU->readSensor();
  Serial.print(IMU->getAccelX_mss(), 6);
  Serial.print("\t");
  Serial.print(IMU->getAccelY_mss(), 6);
  Serial.print("\t");
  Serial.print(IMU->getAccelZ_mss(), 6);
  Serial.print("\t");
  Serial.print(IMU->getGyroX_rads(), 6);
  Serial.print("\t");
  Serial.print(IMU->getGyroY_rads(), 6);
  Serial.print("\t");
  Serial.print(IMU->getGyroZ_rads(), 6);
  Serial.print("\t");
  Serial.print(IMU->getMagX_uT(), 6);
  Serial.print("\t");
  Serial.print(IMU->getMagY_uT(), 6);
  Serial.print("\t");
  Serial.print(IMU->getMagZ_uT(), 6);
  Serial.print("\t");
  Serial.println(IMU->getTemperature_C(), 6);
}
```
produces for me serial outputs such as

18:20:07.032 -> ovf	ovf	ovf	0.031426	0.067246	-0.006924	ovf	ovf	ovf	25.762333

due to uninitialized bias variables e.g. in line 169 of MPU9250.h

best regards
Jan

**Comment by JeroenGar** [comment]
I'm having the exact same issue in one of my sketches. 
Did you just initialize the _axb, _ayb and _azb to 0 to fix it?

**Comment by jtec** [comment]
Hi, 

yeah, that is exactly what i did. Once I find the time I should add init values for all variables and make a merge request.

cheers
Jan

**Comment by flybrianfly** [comment]
Please do submit a pull request. Not sure why the ESP32 compiler is treating those differently and I don't have an ESP32 to test with, but seems like a straightforward fix.

**Comment by JeroenGar** [comment]
I'm running it on the Arduino Due fyi

**Comment by amoghskulkarni** [comment]
Hello,

I am having the exact same issue where all 9 values show `ovf` without the bias correction that @JeroenGar  suggested. After the bias variables being initialized to `0.0f`, values of all 9 variables remain `0.00000`. My sketch is exactly same as that of @jtec. 

How should I debug this?

**Comment by amoghskulkarni** [comment]
Never mind, got it working! Was a connection issue. Still had to initialize the bias variables though.

**Comment by markselias** [comment]
Thanks @skulumani! Please make a pull request for the initialization, that works and IMHO should be definitely in the current code.
