### ISSUE TITLE
Magnetometer calibration breaks if biases and scales were set before

### ISSUE THREAD

**Issue by dbuezas** [bolderflight/invensense-imu#57]
During calibration, the samples from the magnetometer are corrected using the scales and biases already stored.

e.g.: line 897:
```
_hxfilt = (_hxfilt * ((float)_coeff - 1) + (getMagX_uT() / _hxs + _hxb)) / ((float)_coeff);
```
This results in the new biases implicitly being relative to the old ones (which breaks them). A way to test it is to calibrate twice on a row, which results in different values.

I think the same line should be:
```
_hxfilt = (_hxfilt * ((float)_coeff - 1) + getMagX_uT()) / ((float)_coeff);
```
instead.

Amazing lib btw :)

**Comment by korbinianbauer** [comment]
Any updates on this?

**Comment by wlwatkins** [comment]
I've looked at the code, trying to port it to golang, i don't see what `_hxfilt`, `_hyfilt`, `_hzfilt` are as they are not declared to a given value if i'm not mistake.

**Comment by flybrianfly** [comment]
Calibration functionality was removed from this library.
