### ISSUE TITLE
Full Scale Range-Question

### ISSUE THREAD

**Issue by FlorentVllasa** [bolderflight/invensense-imu#69]
What is the purpose of changing this value? I'm using the MPU-9250 with an ESP32 and what I notice is that even when i move the sensor quite heavily the values seem not to got that high. For example i can't differentiate a heavy movement between a slow  movement. Does this have to do something with the Full Scale Range?

Thank you.

**Comment by flybrianfly** [comment]
The full scale range sets the sensor resolution. For example, if you set the full scale range to 500 deg/s, then you will get better resolution than with the range set to 2000 deg/s, but not be able to read values above 500 deg/s.
