### ISSUE TITLE
README does not specify whether magnetometer is automatically calibrated when begin() is called.

### ISSUE THREAD

**Issue by jgannon24** [bolderflight/invensense-imu#71]
The description of calibrateGyro() says "The gyro bias is automatically estimated during the begin() function and removed from sensor measurements." It does not say this in the description of calibrateMag(). Even if the magnetometer is not automatically calibrated when begin() is called, this would be helpful information since because the gyro is automatically calibrated and one might assume all sensors would then be calibrated during the begin() call. Specifying so would eliminate this confusion.

**Comment by Ananfruit** [comment]
Can you share the code when you calibrate your accel and gyro, please? Thanks in advance!
