### ISSUE TITLE
Accelerometer giving constant values

### ISSUE THREAD

**Issue by Syed-Muddassir** [bolderflight/invensense-imu#73]
I've been running the basic I2C example code and i found out that my x-accelerometer is pretty accurate, z-accelerometer is a little inaccurate but my y-accelerometer is giving a constant value of 156.9. Can someone please help in this to debug this problem? What are the chances that it's a hardware issue?

**Comment by Ananfruit** [comment]
Can you share the code when you calibrate your accel and gyro, please? Thanks in advance!

**Comment by Syed-Muddassir** [comment]
my imu was faulty. i replaced it and now it works fine.
