### ISSUE TITLE
Many internal variables are used before initialization that prevent library to work if allocated on heap.

### ISSUE THREAD

**Issue by ddv2005** [bolderflight/invensense-imu#82]
Hello,

It is unbelievable but  many internal variables are used before initialization. For example _gxb, _gyb, _gzb, _axb, _ayb. _azb . It can work if object placed in zero initiated memory block, but in release mode "new" operator always put object to UNINITIALIZED memory block and it does not work. ALL variables before use MUST be initialized even if it should be 0.

**Comment by flybrianfly** [comment]
Should be fixed now.
