### ISSUE TITLE
AccY Data only decreasing

### ISSUE THREAD

**Issue by A-Basra** [bolderflight/invensense-imu#90]
Hi,

I'm having some issues with the AccelY data. When calling the y accel data, using getAccelY_mss(), the data decreases no matter whether you rotate the device along the Y axis forward or backwards as opposed to increasing for movement in one direction and decreasing for the other.

The X axis works fine and as expected by increasing when moved in one direction along the x axis and decreasing when moving in the other.

Any suggestions?

**Comment by flybrianfly** [comment]
Not sure why this would be the case unless there is some confusion about the axes or what is supposed to be measured / returned from an accelerometer.
