### ISSUE TITLE
calibrateGyro not working

### ISSUE THREAD

**Issue by peteole** [bolderflight/invensense-imu#92]
Calibrating the gyro does not work on a gy-91 with an stm32 blue pill and platformio. By debugging I found out that this is due to the following code:
`if (setSrd(19) < 0) {
    return -3;
  }`
Just removing it from the implementation fixes the issue.

**Comment by flybrianfly** [comment]
Calibration isn't included in newer versions of the driver, so we won't pull in any fixes.
