### ISSUE TITLE
Missing Libraries in units.h and eigen.h

### ISSUE THREAD

**Issue by SnowDropZero** [bolderflight/invensense-imu#99]
Even though I included the eigen.h and units.h, I get an error for various libraries not existing. Some examples include "type_traits" and "cmath" and "array". I've included example pictures.

![image](https://user-images.githubusercontent.com/30913016/155440224-95af7fee-8871-433e-a203-8c526415e98d.png)

**Comment by flybrianfly** [comment]
Only ARM based microcontrollers are supported, AVR based microcontrollers like the Uno are not supported.
